---
# tasks file for sa-sentry

  - include: __detect_init_system.yml

  - include: tasks_sentry.yml

  - include: tasks_sentry_plugins.yml
    when: option_install_sentry_plugins

  - include: tasks_sentry_supervisord.yml
    when: option_configure_startup

  - include: tasks_sentry_nginx.yml
    when: option_configure_nginx
