---
# tasks file for sa-sentry
  - include: tasks_sentry.yml

  - include: tasks_sentry_supervisord.yml
    when: option_configure_startup

  - include: tasks_sentry_nginx.yml
    when: option_configure_nginx
