---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-python",
         tags: ["create"] 
       }
     - {
         role: "sa-redis",
         option_install_using_chris_lea_ppa: true,
         tags: ["create", "update"]
       }
     - {
         role: "sa-supervisord",
         tags: ["create"]
       }
     - {
         role: "sa-postgres",
         tags: ["create"]
       }
     - {
         role: "sa-nginx",
         tags: ["create"]
       }
     - {
         role: "sa-uwsgi",
         tags: ["create"]
       }
     - {
         role: "sa-sentry",
         tags: ["create", "update"]
       }




  tasks:

    - debug: msg="Tasks section"



