---
# handlers file for sa-sentry
  - name: restart sentry
    service: name="supervisor" state="restarted"
    become: yes


  - name: restart nginx
    service: name="nginx" state="restarted"
    become: yes

